//! Compiles the vendored dlmdb C sources (lmdb/, pinned in UPSTREAM_COMMIT).

fn main() {
    println!("cargo:rerun-if-changed=lmdb/mdb.c");
    println!("cargo:rerun-if-changed=lmdb/midl.c");
    println!("cargo:rerun-if-changed=lmdb/dlmdb.h");
    println!("cargo:rerun-if-changed=lmdb/midl.h");
    // Prefix every exported symbol: stock LMDB (via heed/lmdb-master-sys in
    // downstream trees) defines the same mdb_* names, and both must link
    // into one binary. The list covers every T/D symbol in mdb.o + midl.o.
    cc::Build::new()
        .file("lmdb/mdb.c")
        .file("lmdb/midl.c")
        .include("lmdb")
        .define("mdb_cmp", "dlmdb_cmp")
        .define("mdb_count_all", "dlmdb_count_all")
        .define("mdb_count_range", "dlmdb_count_range")
        .define("mdb_cursor_close", "dlmdb_cursor_close")
        .define("mdb_cursor_count", "dlmdb_cursor_count")
        .define("mdb_cursor_dbi", "dlmdb_cursor_dbi")
        .define("mdb_cursor_del", "dlmdb_cursor_del")
        .define("mdb_cursor_get", "dlmdb_cursor_get")
        .define("mdb_cursor_get_rank", "dlmdb_cursor_get_rank")
        .define("mdb_cursor_key_rank", "dlmdb_cursor_key_rank")
        .define("mdb_cursor_list_dup", "dlmdb_cursor_list_dup")
        .define("mdb_cursor_open", "dlmdb_cursor_open")
        .define("mdb_cursor_put", "dlmdb_cursor_put")
        .define("mdb_cursor_renew", "dlmdb_cursor_renew")
        .define("mdb_cursor_txn", "dlmdb_cursor_txn")
        .define("mdb_dbi_close", "dlmdb_dbi_close")
        .define("mdb_dbi_flags", "dlmdb_dbi_flags")
        .define("mdb_dbi_open", "dlmdb_dbi_open")
        .define("mdb_dcmp", "dlmdb_dcmp")
        .define("mdb_del", "dlmdb_del")
        .define("mdb_drop", "dlmdb_drop")
        .define("mdb_env_close", "dlmdb_env_close")
        .define("mdb_env_copy", "dlmdb_env_copy")
        .define("mdb_env_copy2", "dlmdb_env_copy2")
        .define("mdb_env_copyfd", "dlmdb_env_copyfd")
        .define("mdb_env_copyfd2", "dlmdb_env_copyfd2")
        .define("mdb_env_create", "dlmdb_env_create")
        .define("mdb_env_get_fd", "dlmdb_env_get_fd")
        .define("mdb_env_get_flags", "dlmdb_env_get_flags")
        .define("mdb_env_get_maxkeysize", "dlmdb_env_get_maxkeysize")
        .define("mdb_env_get_maxreaders", "dlmdb_env_get_maxreaders")
        .define("mdb_env_get_path", "dlmdb_env_get_path")
        .define("mdb_env_get_userctx", "dlmdb_env_get_userctx")
        .define("mdb_env_info", "dlmdb_env_info")
        .define("mdb_env_open", "dlmdb_env_open")
        .define("mdb_env_set_assert", "dlmdb_env_set_assert")
        .define("mdb_env_set_flags", "dlmdb_env_set_flags")
        .define("mdb_env_set_interrupt", "dlmdb_env_set_interrupt")
        .define("mdb_env_set_mapsize", "dlmdb_env_set_mapsize")
        .define("mdb_env_set_maxdbs", "dlmdb_env_set_maxdbs")
        .define("mdb_env_set_maxreaders", "dlmdb_env_set_maxreaders")
        .define("mdb_env_set_userctx", "dlmdb_env_set_userctx")
        .define("mdb_env_stat", "dlmdb_env_stat")
        .define("mdb_env_sync", "dlmdb_env_sync")
        .define("mdb_env_sync0", "dlmdb_env_sync0")
        .define("mdb_get", "dlmdb_get")
        .define("mdb_get_key_rank", "dlmdb_get_key_rank")
        .define("mdb_get_rank", "dlmdb_get_rank")
        .define("mdb_mid2l_append", "dlmdb_mid2l_append")
        .define("mdb_mid2l_insert", "dlmdb_mid2l_insert")
        .define("mdb_mid2l_search", "dlmdb_mid2l_search")
        .define("mdb_midl_alloc", "dlmdb_midl_alloc")
        .define("mdb_midl_append", "dlmdb_midl_append")
        .define("mdb_midl_append_list", "dlmdb_midl_append_list")
        .define("mdb_midl_append_range", "dlmdb_midl_append_range")
        .define("mdb_midl_free", "dlmdb_midl_free")
        .define("mdb_midl_need", "dlmdb_midl_need")
        .define("mdb_midl_search", "dlmdb_midl_search")
        .define("mdb_midl_shrink", "dlmdb_midl_shrink")
        .define("mdb_midl_sort", "dlmdb_midl_sort")
        .define("mdb_midl_xmerge", "dlmdb_midl_xmerge")
        .define("mdb_put", "dlmdb_put")
        .define("mdb_range_count_keys", "dlmdb_range_count_keys")
        .define("mdb_range_count_values", "dlmdb_range_count_values")
        .define("mdb_reader_check", "dlmdb_reader_check")
        .define("mdb_reader_list", "dlmdb_reader_list")
        .define("mdb_set_compare", "dlmdb_set_compare")
        .define("mdb_set_dupsort", "dlmdb_set_dupsort")
        .define("mdb_set_relctx", "dlmdb_set_relctx")
        .define("mdb_set_relfunc", "dlmdb_set_relfunc")
        .define("mdb_stat", "dlmdb_stat")
        .define("mdb_strerror", "dlmdb_strerror")
        .define("mdb_txn_abort", "dlmdb_txn_abort")
        .define("mdb_txn_begin", "dlmdb_txn_begin")
        .define("mdb_txn_commit", "dlmdb_txn_commit")
        .define("mdb_txn_env", "dlmdb_txn_env")
        .define("mdb_txn_id", "dlmdb_txn_id")
        .define("mdb_txn_renew", "dlmdb_txn_renew")
        .define("mdb_txn_reset", "dlmdb_txn_reset")
        .define("mdb_version", "dlmdb_version")
        // dlmdb carries benign unused/sign warnings on modern compilers;
        // the vendored source is pinned, not maintained here.
        .warnings(false)
        .compile("dlmdb");
}
