//! `cljrsh uberscript OUT (-m NS | FILE)` — bundle a program and every
//! source namespace it transitively requires into one self-contained
//! script (babashka's uberscript).
//!
//! Like bb's, the carve is textual and deliberately naive: each reachable
//! namespace's SOURCE FILE is concatenated once, dependencies first.
//! Built-in namespaces (and anything else that doesn't resolve to a file
//! on the source path — pods, native deps) are left as plain `require`s
//! for the target runtime to satisfy.

use std::collections::HashSet;
use std::path::PathBuf;
use std::sync::Arc;

use cljrs_env::env::GlobalEnv;
use cljrs_reader::{Form, FormKind};

pub fn run(globals: &Arc<GlobalEnv>, args: &[String]) -> i32 {
    let usage = "usage: cljrsh uberscript OUT.clj (-m NS | FILE)";
    let (out_path, entry) = match args {
        [out, flag, ns] if flag == "-m" || flag == "--main" => {
            (out.clone(), Entry::Main(ns.clone()))
        }
        [out, file] => (out.clone(), Entry::File(file.clone())),
        _ => {
            eprintln!("{usage}");
            return 2;
        }
    };

    let src_paths: Vec<PathBuf> = globals.source_paths.read().unwrap().clone();
    let mut visited: HashSet<String> = HashSet::new();
    let mut chunks: Vec<String> = Vec::new();

    let entry_src = match &entry {
        Entry::File(path) => match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) => {
                eprintln!("cljrsh: cannot read {path}: {e}");
                return 1;
            }
        },
        Entry::Main(main_sym) => {
            let ns = main_sym.split('/').next().unwrap_or(main_sym);
            match resolve_ns(globals, &src_paths, ns) {
                Some((src, _)) => {
                    visited.insert(ns.to_string());
                    src
                }
                None => {
                    eprintln!("cljrsh: could not find namespace {ns} on the source path");
                    return 1;
                }
            }
        }
    };

    if let Err(e) = bundle(globals, &src_paths, &entry_src, &mut visited, &mut chunks) {
        eprintln!("cljrsh: {e}");
        return 1;
    }
    chunks.push(entry_src);
    if let Entry::Main(main_sym) = &entry {
        let call = if main_sym.contains('/') {
            main_sym.clone()
        } else {
            format!("{main_sym}/-main")
        };
        chunks.push(format!("(apply {call} *command-line-args*)\n"));
    }

    let banner = format!(
        ";; generated by `cljrsh uberscript` {} — do not edit\n",
        crate::opts::VERSION
    );
    let out = format!("{banner}{}", chunks.join("\n"));
    if let Err(e) = std::fs::write(&out_path, out) {
        eprintln!("cljrsh: cannot write {out_path}: {e}");
        return 1;
    }
    println!(
        "Wrote {out_path} ({} bundled namespace{})",
        visited.len(),
        if visited.len() == 1 { "" } else { "s" }
    );
    0
}

enum Entry {
    Main(String),
    File(String),
}

/// Depth-first over SRC's requires: emit each newly seen file-backed
/// namespace (dependencies before dependents) into CHUNKS.
fn bundle(
    globals: &Arc<GlobalEnv>,
    src_paths: &[PathBuf],
    src: &str,
    visited: &mut HashSet<String>,
    chunks: &mut Vec<String>,
) -> Result<(), String> {
    for ns in required_namespaces(src)? {
        if visited.contains(&ns) {
            continue;
        }
        // Builtins (and unresolvable namespaces: pods, natives) stay as
        // plain requires — the target runtime provides them.
        if globals.builtin_source(&ns).is_some() {
            continue;
        }
        let Some((ns_src, _path)) = resolve_ns(globals, src_paths, &ns) else {
            continue;
        };
        visited.insert(ns.clone());
        bundle(globals, src_paths, &ns_src, visited, chunks)?;
        chunks.push(ns_src);
    }
    Ok(())
}

fn resolve_ns(
    _globals: &Arc<GlobalEnv>,
    src_paths: &[PathBuf],
    ns: &str,
) -> Option<(String, String)> {
    let rel = ns.replace('.', "/").replace('-', "_");
    cljrs_env::loader::find_source_file(&rel, src_paths)
}

/// Namespace names required by SRC's top-level `(ns …)` and `(require …)`
/// forms (`:require`/`:use` clauses; quoted symbols and libspec vectors).
fn required_namespaces(src: &str) -> Result<Vec<String>, String> {
    let mut parser = cljrs_reader::Parser::new(src.to_string(), "<uberscript>".into());
    let forms = parser
        .parse_all()
        .map_err(|e| format!("uberscript parse error: {e:?}"))?;
    let mut found = Vec::new();
    for form in &forms {
        let FormKind::List(items) = &form.kind else {
            continue;
        };
        match items.first().map(|f| &f.kind) {
            Some(FormKind::Symbol(s)) if s == "ns" => {
                for clause in &items[1..] {
                    let FormKind::List(clause_items) = &clause.kind else {
                        continue;
                    };
                    if matches!(clause_items.first().map(|f| &f.kind),
                                Some(FormKind::Keyword(k)) if k == "require" || k == "use")
                    {
                        for spec in &clause_items[1..] {
                            collect_libspec(spec, &mut found);
                        }
                    }
                }
            }
            Some(FormKind::Symbol(s)) if s == "require" || s == "use" => {
                for spec in &items[1..] {
                    collect_libspec(unquote(spec), &mut found);
                }
            }
            _ => {}
        }
    }
    Ok(found)
}

/// `'x` reads as `FormKind::Quote` (or a literal `(quote x)` list) — strip it.
fn unquote(form: &Form) -> &Form {
    if let FormKind::Quote(inner) = &form.kind {
        return inner;
    }
    if let FormKind::List(items) = &form.kind
        && items.len() == 2
        && matches!(&items[0].kind, FormKind::Symbol(s) if s == "quote")
    {
        return &items[1];
    }
    form
}

/// A libspec is a bare symbol, `[ns :as a …]`, or a prefix list
/// `(prefix suffix1 suffix2)`.
fn collect_libspec(spec: &Form, out: &mut Vec<String>) {
    match &spec.kind {
        FormKind::Symbol(s) => out.push(s.clone()),
        FormKind::Vector(items) => {
            if let Some(FormKind::Symbol(s)) = items.first().map(|f| &f.kind) {
                out.push(s.clone());
            }
        }
        FormKind::List(items) => {
            // Prefix list: (prefix child1 [child2 :as c] …)
            if let Some(FormKind::Symbol(prefix)) = items.first().map(|f| &f.kind) {
                for child in &items[1..] {
                    match &child.kind {
                        FormKind::Symbol(s) => out.push(format!("{prefix}.{s}")),
                        FormKind::Vector(v) => {
                            if let Some(FormKind::Symbol(s)) = v.first().map(|f| &f.kind) {
                                out.push(format!("{prefix}.{s}"));
                            }
                        }
                        _ => {}
                    }
                }
            }
        }
        _ => {}
    }
}
