[package]
name = "cljrs-process"
version = "0.2.23"
edition = "2024"
description = "Subprocess support for clojurust scripting: blocking sh and spawned child-process handles (cljrs.process namespace)"
license.workspace = true
repository.workspace = true

[dependencies]
cljrs-env     = { workspace = true }
cljrs-interop = { workspace = true }
cljrs-gc      = { workspace = true }
cljrs-value   = { workspace = true }

[dev-dependencies]
cljrs-interp = { workspace = true }
cljrs-reader = { workspace = true }
