(def a (atom {:n 0}))
(swap! a update :n inc)
(swap! a assoc :k :v)
(prn @a)
(def v (volatile! 1))
(vswap! v + 10)
(prn @v)
(def d (delay (do (println "computing") 42)))
(prn (realized? d))
(prn @d @d)
