(prn (cond-> {:a 1} true (assoc :b 2) false (assoc :c 3)))
(prn (some-> {:a {:b 1}} :a :b inc))
(prn (some-> nil :a :b))
(prn (as-> 5 x (* x 2) (- x 3)))
(prn (case 5 1 :one 5 :five :other))
(prn (condp = 3 1 :a 3 :b :else))
(prn (for [x [1 2] y [:a :b]] [x y]))
(doseq [x [1 2]] (println "x" x))
(prn (when-let [v (seq [1])] (first v)))
(prn (if-let [v nil] :yes :no))
