(def m (sorted-map :b 2 :a 1 :c 3))
(println m)
(println (first m))
(println (keys m))
(def s (sorted-set 3 1 2))
(println s)
(println (conj s 0))
(def mb (sorted-map-by > 1 :a 3 :c 2 :b))
(println (keys mb))
(def sb (sorted-set-by (fn [a b] (compare (count a) (count b))) "bb" "a" "ccc"))
(println sb)
