(prn "a\nb")
(prn \x)
(println \x)
(prn :k 'sym "s")
(prn [1 "two" \3 nil])
(prn {:a [1 2]})
(print "no-newline")
(println)
(println (pr-str {"k" 1.5}))
(println (with-out-str (pr :x)))
(prn (symbol "a/b") (keyword "ns" "n"))
