(println (dedupe [1 1 2 2 1]))
(println (distinct [1 2 1 3 2]))
(println (split-with #(< % 3) [1 2 3 4 1]))
(println (partition-by odd? [1 1 2 4 5]))
(println (interleave [1 2 3] [:a :b]))
(println (interpose "," ["a" "b"]))
(println (take-nth 2 (range 8)))
(println (drop-last 2 [1 2 3 4 5]))
(println (butlast [1 2 3]))
(println (flatten [1 [2 [3 [4]]]]))
(println (zipmap [:a :b] [1 2]))
(println (partition 2 3 [:pad] (range 7)))
(println (keep-indexed (fn [i x] (when (odd? i) x)) [:a :b :c :d]))
(println (map-indexed vector [:a :b]))
