(println (reduce-kv (fn [acc k v] (assoc acc v k)) {} {:a 1}))
(println (group-by odd? (range 6)))
(println (frequencies [:a :b :a :a]))
(println (merge-with + {:a 1 :b 2} {:a 10 :c 3}))
(println (apply max-key count ["ab" "abc" "a"]))
(println (apply min-key count ["ab" "abc" "a"]))
(println (sort-by count > ["ab" "a" "abc"]))
(println (sort-by :n [{:n 2} {:n 1}]))
(println (update-in {:a {:b 1}} [:a :b] inc))
(println (assoc-in {} [:x :y] 5))
(println ((fnil inc 0) nil))
(println (update {:a 1} :b (fnil conj []) 2))
