(require '[babashka.fs :as fs])
(def dir (fs/create-temp-dir))
(spit (str dir "/x.txt") "content")
(prn (fs/exists? (str dir "/x.txt")))
(prn (fs/file-name (str dir "/x.txt")))
(prn (fs/extension "a/b/c.tar.gz"))
(fs/create-dirs (str dir "/sub/deep"))
(prn (count (fs/glob dir "**/*.txt")))
(prn (fs/directory? (str dir "/sub")))
(fs/delete-tree dir)
(prn (fs/exists? dir))
