(require '[babashka.fs :as fs])
(def d (fs/create-temp-dir))
(def src (fs/path d "hello.txt"))
(spit src "hello, archives!\n")
(def gz (fs/gzip src))
(prn (fs/file-name gz))
(prn (fs/exists? gz))
(fs/delete src)
(def back (fs/gunzip gz))
(prn (slurp back))
(def zroot (fs/path d "tree"))
(fs/create-dirs (fs/path zroot "sub"))
(spit (fs/path zroot "a.txt") "alpha")
(spit (fs/path zroot "sub" "b.txt") "beta")
(def zf (fs/path d "tree.zip"))
(fs/zip zf [zroot] {:root d})
(prn (fs/exists? zf))
(def out (fs/path d "out"))
(fs/create-dirs out)
(fs/unzip zf {:dir out})
(prn (slurp (fs/path out "tree" "a.txt")))
(prn (slurp (fs/path out "tree" "sub" "b.txt")))
(fs/delete-tree d)
