(require '[babashka.fs :as fs])
(def d (fs/create-temp-dir))
(def f (fs/path d "bin.dat"))
(fs/write-bytes f (byte-array [72 105 33]))
(prn (fs/size f))
(prn (slurp f))
(def bs (fs/read-all-bytes f))
(prn (count bs))
(prn (vec bs))
(def note (fs/path d "note.txt"))
(spit note "one")
(prn (fs/update-file note clojure.string/upper-case))
(prn (slurp note))
(prn (fs/split-paths "/a:/b/c"))
(prn (pos? (count (fs/which-all "sh"))))
(prn (pos? (fs/creation-time f)))
(fs/delete-tree d)
