[package]
name = "cljrs-tx"
version = "0.2.27"
edition = "2024"
description = "GC-less isolated transaction-function runtime for clojurust"
license.workspace = true
repository.workspace = true

[features]
default = ["host-dependencies"]
host-dependencies = [
    "cljrs-env/host-dependencies",
    "cljrs-interp/host-dependencies",
]
no-gc = [
    "cljrs-gc/no-gc",
    "cljrs-value/no-gc",
    "cljrs-env/no-gc",
    "cljrs-interp/no-gc",
]

[dependencies]
cljrs-gc = { workspace = true }
cljrs-types = { workspace = true }
cljrs-value = { workspace = true }
cljrs-reader = { workspace = true }
cljrs-env = { path = "../cljrs-env", version = "0.2.27", default-features = false }
cljrs-interp = { path = "../cljrs-interp", version = "0.2.27", default-features = false }
thiserror = { workspace = true }
